# Generated by Django 3.2.9 on 2021-12-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='residence',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
