# Generated by Django 3.2.9 on 2021-12-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_residence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='residence',
        ),
        migrations.AddField(
            model_name='user',
            name='main_city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sub_city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
