# Generated by Django 4.0rc1 on 2021-12-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211205_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='main_city',
            field=models.CharField(blank=True, choices=[('seoul', '서울특별시'), ('incheon', '인천광역시'), ('deagu', '대구광역시'), ('gwangju', '광주광역시'), ('deajeon', '대전광역시'), ('ulsan', '울산광역시'), ('sejong', '세종특별자치시'), ('busan', '부산광역시'), ('gyeonggi', '경기도'), ('kangwon', '강원도'), ('chungbuk', '충청북도'), ('cjungnam', '충청남도'), ('gyeongbuk', '경상북도'), ('gyeongnam', '경상남도'), ('jeonbuk', '전라북도'), ('jeonnam', '전라남도'), ('jeju', '제주특별자치도')], max_length=30, null=True),
        ),
    ]
