# Generated by Django 3.2.9 on 2021-12-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('register_period_begin', models.DateTimeField(null=True)),
                ('register_period_end', models.DateTimeField(null=True)),
                ('election_period_begin', models.DateTimeField(null=True)),
                ('election_period_end', models.DateTimeField(null=True)),
                ('election_type', models.CharField(choices=[('president_election', '대통령 선거'), ('mayor_election', '시장 선거'), ('parliamentary_election', '국회의원 선거')], max_length=40, null=True)),
            ],
        ),
    ]
