# Generated by Django 3.2.9 on 2021-12-11 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True, null=True)),
                ('symbol', models.IntegerField(blank=True, null=True)),
                ('party', models.CharField(blank=True, max_length=100)),
                ('name_kor', models.CharField(blank=True, max_length=100)),
                ('name_hanja', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(blank=True, max_length=100)),
                ('birth', models.DateField(blank=True, null=True)),
                ('job', models.CharField(blank=True, max_length=100)),
                ('educational_background', models.CharField(blank=True, max_length=100)),
                ('career', models.CharField(blank=True, max_length=100)),
                ('bulletin', models.FileField(blank=True, upload_to='pdf')),
                ('poster', models.FileField(blank=True, upload_to='pdf')),
                ('pledge', models.FileField(blank=True, upload_to='pdf')),
                ('candidate', models.CharField(max_length=10)),
                ('status', models.CharField(blank=True, choices=[('waiting', '승인 대기 중'), ('accepted', '승인 완료'), ('rejected', '거절됨')], max_length=30, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.election')),
            ],
        ),
    ]
