# Generated by Django 3.2.9 on 2021-11-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=1000)),
                ('poster', models.FileField(upload_to='posters')),
                ('candidate', models.CharField(max_length=10)),
                ('election', models.CharField(max_length=200)),
            ],
        ),
    ]
