# Generated by Django 3.2.9 on 2021-12-13 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
        ('promotion', '0002_alter_promotion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='elections.election'),
        ),
    ]
