# Generated by Django 3.2.9 on 2021-12-05 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_auto_20211205_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='published_date',
        ),
    ]
