# Generated by Django 3.2.9 on 2021-12-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_auto_20211205_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='content',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='poster',
        ),
        migrations.AddField(
            model_name='promotion',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
