# Generated by Django 3.2.9 on 2021-12-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_auto_20211205_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='bulletin',
            field=models.FileField(blank=True, upload_to='pdf'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='career',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='educational_background',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='job',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='name_hanja',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='name_kor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='party',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='pledge',
            field=models.FileField(blank=True, upload_to='pdf'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='poster',
            field=models.FileField(blank=True, upload_to='pdf'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='sex',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='promotion',
            name='symbol',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
