# Generated by Django 3.2.9 on 2021-12-11 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
        ('promotion', '0005_auto_20211206_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='status',
            field=models.CharField(blank=True, choices=[('waiting', '승인 대기 중'), ('accepted', '승인 완료'), ('rejected', '거절됨')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.election'),
        ),
    ]
