# Generated by Django 3.2.9 on 2021-12-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='poster',
            field=models.FileField(blank=True, null=True, upload_to='posters'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
